### ISSUE TITLE
If user has discontinued non-DCH drivers, DCH drivers will not be shown if available

### ISSUE THREAD

**Issue by ElPumpo** [ZenitH-AT/nvidia-update#6]
See https://github.com/ElPumpo/TinyNvidiaUpdateChecker/issues/130

Basicly a DCH driver migration

**Comment by ZenitH-AT** [comment]
Fixed by https://github.com/ZenitH-AT/nvidia-update/commit/86aa8f415528244d69ab9e9703de5256c8a1e610.

I overengineered it a little so that users can choose if they want to install the non-DCH driver (e.g. in the case that their GPU is no longer supported and the latest non-DCH driver for them is the same as the latest DCH one).
