### ISSUE TITLE
Log file location and No User Intervention required for Automation

### ISSUE THREAD

**Issue by Pkistampally** [ZenitH-AT/nvidia-update#9]
Hello Robert,
I have tested the previous modification for local file downloads for gpu-data.jason and OS-data.jason file and it worked perfectly fine...
except few things below.  
when I ran the script it is waiting for user input for example,,  select YEs or NO for new Driver download and Presss any Key to exist the script after the completion... 
above are good when we do for Individual users and for checking to see where the script is stopping but it is not for bulk deployment where there shouldnt be any user intervention.
also can you please add the logging in the script to a local file so that we can refer to that file once completed and see what exactly going on if there is an error..

kindly please add the above 3 when possible..
I have currently hashed the below lines from the code for mass deployment
![image](https://user-images.githubusercontent.com/63632201/210761300-ab09a1e3-970e-41f9-8ea2-9c666808f3bd.png)
![image](https://user-images.githubusercontent.com/63632201/210761343-b20e7244-d063-4059-b151-1a99286ddfc0.png)
![image](https://user-images.githubusercontent.com/63632201/210761371-305a74fc-2039-4869-9a84-71182131081a.png)

**Comment by Pkistampally** [comment]
![image](https://user-images.githubusercontent.com/63632201/210761647-d9528b84-95f0-4e25-8145-00de6103ebf4.png)

**Comment by Pkistampally** [comment]
This could be an Enhancement but not a bug

**Comment by ZenitH-AT** [comment]
Yeah, running the script silently, using all the default options for any prompts, is one thing I have been thinking of adding for a while, which would make the scheduled task system a lot more useful.

Naturally, running the script silently would output everything to a timestamped text file in a configurable location.

I don't have much time to work on nvidia-update this month but it'll be the next thing I implement in the coming weeks.

**Comment by Pkistampally** [comment]
Thank you for the Update Robert. Appreciate your time in working on this for community like this.
for now, as I shown above screen shorts, I have commented the code and ran through without any issues, but logging is the only thing missing. do you know what the other issues are I will have if I comment all those lines above which showed in my screen shot apart from script going in silent mode.

**Comment by ZenitH-AT** [comment]
There may actually be some issues. Commenting out the "press any key to exit" related code is fine but for the `$decision = ...` stuff, you should rather just change the value being assigned to the default values.

It shouldn't really matter since the logic is such that the default option isn't handled in if statements but it's best to actually have the `$decision` variable set rathern than comment it out, just in case.

Example:

```ps1
$decision = $Host.UI.PromptForChoice("", "`nDo you want to download and install the latest driver?", $options, 0)
```

Changes to:

```ps1
$decision = 0
```

Where `0` is the default option index (at the end of the original line). You'd basically just search for "$decision =" in the script and modify those lines accordingly to make the script run in a sort of silent mode.

---

When I get around to updating the script I'll have to move the `PromptForChoice()` related code to a separate function whose behaviour is based on whether the script is being run in silent mode.

---

For logging, I just need to redirect all output to a text file right before the script exits. The only issue I can think of is stuff like the loading wheel when the driver is being downloaded. I also want to standardise some of the output messages, since not every one writes a timestamp.

So it might be pretty simple to do a basic implementation but doing it the "right way" (if someone with my experience can even say that) may take some time.

**Comment by ZenitH-AT** [comment]
A new release will be ready this weekend, adding a `-Silent` and `-LogFilePath` optional parameters.

EDIT: I'll release it later today, still need to do some testing. Logs implementation isn't perfect but should suffice for now.

**Comment by Pkistampally** [comment]
Awesome, That’s really a great news. Thank you for doing this for the community.


Thank you,
Pavan Kistampally

**Comment by ZenitH-AT** [comment]
Fixed by https://github.com/ZenitH-AT/nvidia-update/commit/385e7be52232d2af239252d2d682d90ab0f71917; new release.

The logging implementation isn't fully comprehensive but can be improved in the future as needed.
